# Generated by Django 2.2.12 on 2020-08-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=143, verbose_name='Заголовок')),
                ('date', models.CharField(max_length=13, verbose_name='Дата')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
        ),
    ]
