# Generated by Django 2.2.12 on 2020-07-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Под кадегория',
                'verbose_name_plural': 'Под кадегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=50, verbose_name='Осн. ед изм.')),
                ('full_name', models.CharField(max_length=120, verbose_name='Полное наименование')),
                ('nds', models.CharField(max_length=20, verbose_name='Ставка НДС')),
                ('country_of_origin', models.CharField(blank=True, max_length=120, null=True, verbose_name='Страна происхождения')),
                ('gdt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ГДТ')),
                ('storage_life', models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок хранения')),
                ('storage_conditions', models.TextField(blank=True, null=True, verbose_name='Условия хранения')),
                ('cert_of_conformity', models.CharField(blank=True, max_length=250, null=True, verbose_name='Сертификат соответствия')),
                ('gost_ty', models.TextField(blank=True, null=True, verbose_name='Нормативно технический документ (ГОСТ, ТУ)')),
                ('basic_property', models.TextField(blank=True, null=True, verbose_name='Основное свойство')),
                ('print_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование для печати')),
                ('articule', models.TextField(blank=True, null=True, verbose_name='Артикул')),
                ('edizm_base', models.CharField(blank=True, max_length=200, null=True, verbose_name='Базовая ед изм.')),
                ('base_weight', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вес Базовый (кг)')),
                ('base_barcode', models.TextField(blank=True, null=True, verbose_name='Штрихкод базовый')),
                ('remains', models.FloatField(blank=True, null=True, verbose_name='Остаток')),
                ('reserve_on_firm', models.FloatField(blank=True, null=True, verbose_name='Резерв по фирме')),
                ('remains_fact', models.FloatField(blank=True, null=True, verbose_name='Остаток факт.')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('val', models.TextField(blank=True, null=True, verbose_name='Вал')),
                ('purchase', models.FloatField(blank=True, null=True, verbose_name='Закупка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.SubCategory')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
