// import 'jquery-migrate/dist/jquery-migrate.min'
import './lib/config'
import './lib/slick'
import './lib/parallax'
import './lib/sticky_header'
import './lib/slideout'
import './lib/yamaps'
import './lib/feedback'
import './lib/hello'
