# Generated by Django 2.2.12 on 2020-08-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=63, verbose_name='Описание')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
