# Generated by Django 2.2.12 on 2020-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20200812_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'ordering': ['-published'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Описание'),
        ),
    ]
